version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 10
    groups:
      development:
        patterns:
          - "pyright"
          - "ruff"
          - "pre-commit"
          - "build"
          - "hatchling"
          - "pyinstrument"
          - "scalene"
      production:
        patterns:
          - "python-dotenv"
          - "rich"
          - "typer"
          - "par-ai-core"
          - "PyYAML"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5